dataset:
  name: mnist
  batch_size: 2048
  train_prop: 0.9

loss:
  name: elbo
  output: bernouilli
  posterior: normal
  lr: 0.0001
  epochs: 200
  ksi: 0
  early_stopping:

model:
  seed: 0
  h: 200
  d: 50
  activation: relu
  n_layers: 2

defaults:
  - _self_

hydra:
  job:
    chdir: true
  run:
    dir: ./outputs/${loss.name}_${now:%Y-%m-%d}/${now:%H-%M-%S}